### ISSUE TITLE
上游资源无法访问

### ISSUE THREAD

**Issue by nb5p** [jae-jae/Userscript-Plus#101]
脚本引用的资源 https://greasyfork.org/scripts/430303-l-lib2-js/code/l-lib2js.js 已被上游删除，请调整脚本内容，谢谢。

**Comment by yuzhouwww** [comment]
I've upload a repaired version:
https://greasyfork.org/zh-CN/scripts/440498-userscript-show-site-all-userjs-repaired

**Comment by yuzhouwww** [comment]
and i will create a pr soon

**Comment by nb5p** [comment]
it works, thx.
