### ISSUE TITLE
userscript下载到这个脚本，有1400K，3w行代码，你是如何敲到TamperMonkey的编辑器中去的？

### ISSUE THREAD

**Issue by chapgaga** [jae-jae/Userscript-Plus#12]
那页面编辑器太弱了，能放得进这么多代码么：（

**Comment by jae-jae** [comment]
在页面动态注入JS，不需要都放到编辑器里面去

**Comment by chapgaga** [comment]
你这3w行代码，是用什么打包的？不会是一开始就编辑这么个大文件吧？
我一般喜欢用RequireJS划分很多模块，这样代码看起来更清晰，可是TamperMonkey好像不能使用RequireJS

**Comment by jae-jae** [comment]
webpack
