### ISSUE TITLE
ljs和base这两个依赖获取失败

### ISSUE THREAD

**Issue by bayuexiong** [jae-jae/Userscript-Plus#15]
-// @require      https://greasyfork.org/scripts/23419-l-js/code/ljs.js
-// @require      https://greasyfork.org/scripts/23420-userjs-base-js/code/userjs-basejs.js
+// @require      https://greasyfork.org/scripts/23419-l-js/code/ljs.js?version=148792
+// @require      https://greasyfork.org/scripts/23420-userjs-base-js/code/userjs-basejs.js?version=214700

我把版本号去掉就好了，是不是那边规则改动了什么

**Comment by dawangraoming** [comment]
Chrome出现同样的错误
`Execution of script 'Userscript+ : Show Site All UserJS' failed! ljs is not defined`

@bayuexiong 去除版本号可以解决，感谢提供的解决方案。

**Comment by jae-jae** [comment]
原因不明，感谢给出的解决方案

**Comment by jae-jae** [comment]
已修复 fixed
