### ISSUE TITLE
希望可以开发一个独立的Firefox扩展版本

### ISSUE THREAD

**Issue by etjim** [jae-jae/Userscript-Plus#17]
希望可以开发一个像“独立的Chrome插件版本”的Firefox扩展版本

**Comment by Rictusempra** [comment]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension

Perhaps something helpful

**Comment by jae-jae** [comment]
Firefox版本已上线：[https://addons.mozilla.org/zh-CN/firefox/addon/userscript-for-tampermonkey/](https://addons.mozilla.org/zh-CN/firefox/addon/userscript-for-tampermonkey/)
