### ISSUE TITLE
捐助链接请使用 Https

### ISSUE THREAD

**Issue by EINDEX** [jae-jae/Userscript-Plus#2]
RT

**Comment by jae-jae** [comment]
是https呀：https://paypal.me/jaepay

**Comment by EINDEX** [comment]
![jietu20170904-105222](https://user-images.githubusercontent.com/13883964/30010010-4ca267fc-915f-11e7-98d1-eff816d6a3b2.jpg)
http://ww1.sinaimg.cn/large/7de3675bly1fizyy2pivwj2074074js6.jpg
![jietu20170904-105235](https://user-images.githubusercontent.com/13883964/30010011-4f6f405e-915f-11e7-83bf-a7892a03d55c.jpg)
http://ww1.sinaimg.cn/large/7de3675bly1fizyyh7m7yj20ci0ciwfl.jpg
![jietu20170904-105253](https://user-images.githubusercontent.com/13883964/30010012-510beb4c-915f-11e7-9dbd-d3b24144b10b.jpg)
http://ww1.sinaimg.cn/large/7de3675bly1fizzsw92owj207s03s748.jpg

我说的是这三个链接哦
