### ISSUE TITLE
不支援一些網站

### ISSUE THREAD

**Issue by maple3142** [jae-jae/Userscript-Plus#29]
例如 https://www.gamer.com.tw/ 找不到任何腳本
但是 https://greasyfork.org/zh-TW/scripts/by-site/gamer.com.tw.json 有很多資料

我想應該是 https://github.com/jae-jae/Userscript-Plus/blob/cf17b05a0c5c2f9e8888b821fa7dfb31f47c9091/src/common/js/tools.js#L9 的問題，它會把 `www.gamer.com.tw` 變成 `com.tw`

**Comment by maple3142** [comment]
我認為使用 [Public Suffix List](https://publicsuffix.org/list/) 可能會比較可靠，上面有各種域名地後綴

**Comment by jae-jae** [comment]
已经使用了一个专业的包来解决这个问题：https://github.com/wrangr/psl
