### ISSUE TITLE
脚本会在后台请求广告

### ISSUE THREAD

**Issue by fuxuejun** [jae-jae/Userscript-Plus#33]
脚本会在后台请求 api.jae.sh

![snipaste20180927_103920](https://user-images.githubusercontent.com/1287755/46120369-f1314180-c241-11e8-916a-71b533f1ef9e.png)
![snipaste20180927_103955](https://user-images.githubusercontent.com/1287755/46120373-f2fb0500-c241-11e8-992b-406dc44d6b31.png)
![snipaste20180927_103657](https://user-images.githubusercontent.com/1287755/46120375-f42c3200-c241-11e8-8aed-07fe90aff839.png)

**Comment by jae-jae** [comment]
实验性功能，后期会移除
