### ISSUE TITLE
老哥你的jae.sh域名证书过期了，老是提示连接失败

### ISSUE THREAD

**Issue by OiCkilL** [jae-jae/Userscript-Plus#36]
![2019-01-28 3 31 14](https://user-images.githubusercontent.com/613988/51820882-2219a400-2312-11e9-88e6-537e5deeec59.png)
![2019-01-28 3 34 19](https://user-images.githubusercontent.com/613988/51820909-35c50a80-2312-11e9-8d6f-f8472031b350.png)

**Comment by jae-jae** [comment]
感谢提醒，已修复。
