### ISSUE TITLE
和Super_preloaderPlus_one冲突了

### ISSUE THREAD

**Issue by Reveanime** [jae-jae/Userscript-Plus#5]
https://greasyfork.org/zh-CN/scripts/10433-super-preloaderplus-one

不知道为什么和这个翻页脚本冲突了，开了这个翻页脚本就不显示了。

**Comment by jae-jae** [comment]
![uc11111](https://user-images.githubusercontent.com/5620429/31313594-e1f1ea74-ac19-11e7-9445-ebe4bb3d65f0.gif)
看图，貌似并不存在你说的问题？

**Comment by Reveanime** [comment]
刚刚我把翻页脚本删了重装没有问题了
谢谢回复
