### ISSUE TITLE
运行无效

### ISSUE THREAD

**Issue by BIQIBAOlaopangxie** [jae-jae/Userscript-Plus#73]
脚本安装后，右下角无可用脚本提示，但油猴显示脚本运行中，求解。

**Comment by jae-jae** [comment]
没有出现弹框的的主要原因是网络问题引起，可以通过安装 Userscript+ Chrome插件版本来得到更好的体验，获取Chrome插件版本的方法：
- 打开 Userscript+ 项目地址： https://github.com/jae-jae/Userscript-Plus/tree/master/crx
- 下载项目中的 `extension.crx` 文件
- 将文件 `extension.crx` 后缀改成 .zip 格式，并解压插件
- 在 Chrome 插件界面打开 `开发者模式`, 并使用`加载已解压的扩展程序`功能加载解压的插件
- 搞定，效果如下图
![](https://raw.githubusercontent.com/jae-jae/_resources/master/img/175033.png)

**Comment by BIQIBAOlaopangxie** [comment]
已解决，感谢🙏🏼😁

**Comment by Aberion** [comment]
万分感谢！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jaeger(黄杰)"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月23日(星期六) 晚上9:50
收件人:&nbsp;"jae-jae/Userscript-Plus"<Userscript-Plus@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [jae-jae/Userscript-Plus] 运行无效 (#73)





 
没有出现弹框的的主要原因是网络问题引起，可以通过安装 Userscript+ Chrome插件版本来得到更好的体验，获取Chrome插件版本的方法：
  
打开 Userscript+ 项目地址： https://github.com/jae-jae/Userscript-Plus/tree/master/crx
 
下载项目中的 extension.crx 文件
 
将文件 extension.crx 后缀改成 .zip 格式，并解压插件
 
在 Chrome 插件界面打开 开发者模式, 并使用加载已解压的扩展程序功能加载解压的插件
 
搞定，效果如下图
