### ISSUE TITLE
在 Windows Firefox 56 提示没有展示 

### ISSUE THREAD

**Issue by gclove** [jae-jae/Userscript-Plus#8]
GreasyFork 和 Github 都有测试

MAC 版本没有测试

**Comment by jhdxr** [comment]
相同问题+1.
右下角会显示空白的框，但没有具体内容

**Comment by PFZheng** [comment]
mac firefox 59 上不工作了

**Comment by jae-jae** [comment]
Firefox版本已上线：https://addons.mozilla.org/zh-CN/firefox/addon/userscript-for-tampermonkey/
