### ISSUE TITLE
Chrome 乱码

### ISSUE THREAD

**Issue by killbus** [jae-jae/Userscript-Plus#87]
![Screenshot_20210310_185507](https://user-images.githubusercontent.com/358214/110618981-3bb89580-81d2-11eb-8589-e72d5da824a5.png)

我的 Chrome 显示乱码，Firefox 是正常的。是我遗漏了什么吗？

版本：2.3.8
扩展：violentmonkey  2.12.10

**Comment by jae-jae** [comment]
是只有某个网站这样，还是所有网站都这样？

**Comment by jae-jae** [comment]
在某些网站因为安全策略的原因，导致插件字体文件无法加载，就会出现这种现象
