### ISSUE TITLE
Greasyfork 脚本好像不全？很多脚本都没有...

### ISSUE THREAD

**Issue by XIU2** [jae-jae/Userscript-Plus#98]
找了几个网站试了下，好像不全呀。  
我的所有脚本都看不到，哪怕我的脚本在**匹配域名页面排前几**甚至**排第一**也看不到。  
反而会看到一些**几年没更新**的脚本？例如：  
- **知乎增强** - _https://greasyfork.org/zh-CN/scripts/419081_  
- **Github 增强** - _https://greasyfork.org/zh-CN/scripts/412245_  
- 我的其他脚本 - _https://greasyfork.org/zh-CN/users/457025 / https://github.com/XIU2/UserScript_

**Comment by Gslw** [comment]
> 找了几个网站试了下，好像不全呀。 我的所有脚本都看不到，哪怕我的脚本在**匹配域名页面排前几**甚至**排第一**也看不到。 反而会看到一些**几年没更新**的脚本？例如：
> 
> * **知乎增强** - _https://greasyfork.org/zh-CN/scripts/419081_
> * **Github 增强** - _https://greasyfork.org/zh-CN/scripts/412245_
> * 我的其他脚本 - _https://greasyfork.org/zh-CN/users/457025 / https://github.com/XIU2/UserScript_

大佬出个替代品啊!
